Repository jacksmith1009/test-auto-shop, pull requests merged in 2023-03, with the labels that each got.

#1 Sparrow/configure frontend backend
  backend/.env
  backend/.gitignore
  backend/package.json
  backend/src/models/User.js
  backend/src/routes/auth.js
  backend/src/server.js
  backend/src/utils/nodeMailerHelpers.js
  frontend/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/main/Advertisement/JwtShow.js
  frontend/src/main/Advertisement/SuccessSignUp.js
  frontend/src/main/authPage/LoginPage.js
  frontend/src/main/authPage/SignUp.js
  frontend/src/main/protectedRoutes/ProtectedRoutes.js
Labels: documentation, enhancement, help wanted

#2 Implementation of auto password
  backend/package.json
  backend/src/routes/auth.js
  frontend/src/main/authPage/SignUp.js
Labels: bug, documentation, enhancement, help wanted

#3 Middleware
  backend/src/middlewares/authMiddleware.js
  backend/src/routes/auth.js
Labels: documentation, enhancement

#4 Added navbar, sidebar and vehicle form
  backend/src/models/VehicleSchema.js
  frontend/src/App.js
  frontend/src/components/AddVehicleForm.js
  frontend/src/globalComponents/NavBar.js
  frontend/src/globalComponents/Sidebar.js
  frontend/src/utils.js
Labels: enhancement
